
spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/management?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0